spring.application.name=tournament

spring.datasource.url=jdbc:mysql://localhost:3306/tournament?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

server.servlet.context-path=/api
